
project_id = "bofaqytiyycmgbqbmctd"

[functions.create-crime-case]
verify_jwt = false

[functions.create-interrogation-answer]
verify_jwt = false

[functions.create-solution-attempt]
verify_jwt = false

[functions.fetch-case-evidences]
verify_jwt = false

[functions.fetch-case-motives]
verify_jwt = false

[functions.fetch-case-suspects]
verify_jwt = false

[functions.fetch-case-witnesses]
verify_jwt = false

[functions.fetch-crime-cases]
verify_jwt = false

[functions.fetch-crime-scene]
verify_jwt = false

[functions.fetch-single-crime-case]
verify_jwt = false

[functions.fetch-solution-attempts]
verify_jwt = false

[functions.get-question-answers]
verify_jwt = false

[functions.list-interrogations]
verify_jwt = false

[functions.prompt-template-identifiers]
verify_jwt = false

[functions.prompt-template-versions]
verify_jwt = false

[functions.prompt-template]
verify_jwt = false
