// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bofaqytiyycmgbqbmctd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvZmFxeXRpeXljbWdicWJtY3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzk3OTIsImV4cCI6MjA2NTc1NTc5Mn0.POhMr7r94ZemqoCC0UDnsM7L3G_H8cXH3zkO1YjEahk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);